### ISSUE TITLE
无法获取视频网址

### ISSUE THREAD

**Issue by makelove** [YangXiaoP/weChatVideoPlay#1]
报错：Setting data field "videUrl" to undefined is invalid.
-
一开始在【小程序开发工具】能获取到视频网址
但在手机微信上报这个错，打开【调试】不行，不检查域名也不行

-
后来在【小程序开发工具】不能获取到视频网址了

**Comment by YangXiaoP** [comment]
这个错误是由于播放下一段视频，取不到数据传输的，写Demo的时候没注意到。但是qqvideo.js文件和方法本身是没问题的，可以直接拉这个文件到你的项目中使用。

**Comment by makelove** [comment]
好的，我再试试。谢谢
