### ISSUE TITLE
第50行 有问题

### ISSUE THREAD

**Issue by w8w8w8** [YangXiaoP/weChatVideoPlay#12]
fn_pre, magic_str, video_type = filename.split('.')

这样的写法，js里面好像是不行的

var ss = filename.split('.');
 fn_pre = ss[0]; magic_str=ss[1]; video_type = ss[2] ;
这样吧，分割出来传给变量

**Comment by sugarkingdom** [comment]
fn_pre, magic_str, video_type = filename.split('.')
改成
[fn_pre, magic_str, video_type] = filename.split('.')
就行了。
