### ISSUE TITLE
访问 123.6.26.156 的请求遭到拒绝

### ISSUE THREAD

**Issue by lihuangshuaige** [YangXiaoP/weChatVideoPlay#2]
访问 123.6.26.156 的请求遭到拒绝   这是什么意思啊

**Comment by YangXiaoP** [comment]
能把报错的原信息复制过来吗？
1.如果你的小程序发布了，需要在微信后台设置配置域名为:https://vv.video.qq.com。
2.有些有版权的视频，如热播的电视剧，是无法完整播放的。
3.有可能你的vid复制错了。
