### ISSUE TITLE
某些特定视频并不能显示

### ISSUE THREAD

**Issue by DevilSoulcz** [YangXiaoP/weChatVideoPlay#3]
发现分片拿的时候似乎有问题,测试获取一部分视频可以正常获取，但是某些视频比如 vid 为 v0701dgxh96 的获取出来的path 是 undefined ..

**Comment by jsaon-L** [comment]
k0701quecaw 也不能 获取  想问下不能获取要怎么办呢

**Comment by YangXiaoP** [comment]
暂时把qqVideo.js文件第36行改为:var filename = data['vl']['vi'][0]['fn'];
因为最近比较忙，没有空整理更新新的代码。

**Comment by YangXiaoP** [comment]
已更新代码，腾讯视频链接为'https://v.qq.com/x/cover/XXXX'和'https://v.qq.com/x/page/XXXXX'的，现在都可以播放
